package View;

import Controller.AdminController;
import Model.Member;
import Model.MemberShipCard;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class MemberView extends javax.swing.JFrame {

    AdminController ac=new AdminController();
    public MemberView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        pnlLeftSide = new java.awt.Panel();
        btnAddMember = new javax.swing.JButton();
        btnDashbord = new javax.swing.JButton();
        btnViewMemberDetails = new javax.swing.JButton();
        pnlMainCard = new java.awt.Panel();
        subPnlDashbord = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        subPnlAdding = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPassword1 = new javax.swing.JPasswordField();
        txtCardNumber = new javax.swing.JTextField();
        txtExpireDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        btnViewMemberDataArr = new javax.swing.JButton();
        btnSaveDB = new javax.swing.JButton();
        subPnlView = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(255, 204, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLeftSide.setBackground(new java.awt.Color(51, 0, 51));
        pnlLeftSide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnAddMember.setBackground(new java.awt.Color(255, 204, 255));
        btnAddMember.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnAddMember.setText("Add new member");
        btnAddMember.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 4, new java.awt.Color(0, 255, 204)));
        btnAddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMemberActionPerformed(evt);
            }
        });

        btnDashbord.setBackground(new java.awt.Color(255, 204, 255));
        btnDashbord.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnDashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dashboard1.png"))); // NOI18N
        btnDashbord.setText("Dashbord");
        btnDashbord.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 4, new java.awt.Color(0, 255, 204)));
        btnDashbord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashbordActionPerformed(evt);
            }
        });

        btnViewMemberDetails.setBackground(new java.awt.Color(255, 204, 255));
        btnViewMemberDetails.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnViewMemberDetails.setText("View member Details");
        btnViewMemberDetails.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 4, new java.awt.Color(0, 255, 204)));
        btnViewMemberDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMemberDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLeftSideLayout = new javax.swing.GroupLayout(pnlLeftSide);
        pnlLeftSide.setLayout(pnlLeftSideLayout);
        pnlLeftSideLayout.setHorizontalGroup(
            pnlLeftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftSideLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(pnlLeftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddMember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewMemberDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(pnlLeftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLeftSideLayout.createSequentialGroup()
                    .addContainerGap(23, Short.MAX_VALUE)
                    .addComponent(btnDashbord, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        pnlLeftSideLayout.setVerticalGroup(
            pnlLeftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftSideLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(btnAddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnViewMemberDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(pnlLeftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlLeftSideLayout.createSequentialGroup()
                    .addGap(132, 132, 132)
                    .addComponent(btnDashbord, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(346, Short.MAX_VALUE)))
        );

        panel1.add(pnlLeftSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 520));

        pnlMainCard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlMainCard.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Dashbord");

        javax.swing.GroupLayout subPnlDashbordLayout = new javax.swing.GroupLayout(subPnlDashbord);
        subPnlDashbord.setLayout(subPnlDashbordLayout);
        subPnlDashbordLayout.setHorizontalGroup(
            subPnlDashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPnlDashbordLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );
        subPnlDashbordLayout.setVerticalGroup(
            subPnlDashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPnlDashbordLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1)
                .addContainerGap(349, Short.MAX_VALUE))
        );

        pnlMainCard.add(subPnlDashbord, "card2");

        subPnlAdding.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add New Member");
        subPnlAdding.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 32, 257, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Member Card ID");

        txtId.setBackground(new java.awt.Color(51, 0, 51));
        txtId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtName.setBackground(new java.awt.Color(51, 0, 51));
        txtName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Name");

        txtContact.setBackground(new java.awt.Color(51, 0, 51));
        txtContact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtContact.setForeground(new java.awt.Color(255, 255, 255));
        txtContact.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Contact Info");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("User Name");

        txtUserName.setBackground(new java.awt.Color(51, 0, 51));
        txtUserName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(255, 255, 255));
        txtUserName.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Password");

        txtPassword1.setBackground(new java.awt.Color(51, 0, 51));
        txtPassword1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPassword1.setForeground(new java.awt.Color(255, 255, 255));

        txtCardNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtExpireDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel9.setText("Expire Date");

        jLabel10.setText("Card Number");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtExpireDate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel2Layout.createSequentialGroup()
                    .addGap(167, 167, 167)
                    .addComponent(txtPassword1)
                    .addGap(30, 30, 30)))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExpireDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(15, 15, 15))
            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel2Layout.createSequentialGroup()
                    .addGap(188, 188, 188)
                    .addComponent(txtPassword1)
                    .addGap(81, 81, 81)))
        );

        subPnlAdding.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 460, 300));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setText("Clear Data");
        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        subPnlAdding.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 130, 30));

        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubmit.setText("Submit Data");
        btnSubmit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        subPnlAdding.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 130, 30));

        btnViewMemberDataArr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewMemberDataArr.setText("Display Data");
        btnViewMemberDataArr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnViewMemberDataArr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMemberDataArrActionPerformed(evt);
            }
        });
        subPnlAdding.add(btnViewMemberDataArr, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 130, 30));

        btnSaveDB.setText("Save DataBase");
        btnSaveDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDBActionPerformed(evt);
            }
        });
        subPnlAdding.add(btnSaveDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, -1, -1));

        pnlMainCard.add(subPnlAdding, "card3");

        jLabel3.setText("View member data");

        javax.swing.GroupLayout subPnlViewLayout = new javax.swing.GroupLayout(subPnlView);
        subPnlView.setLayout(subPnlViewLayout);
        subPnlViewLayout.setHorizontalGroup(
            subPnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPnlViewLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );
        subPnlViewLayout.setVerticalGroup(
            subPnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPnlViewLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel3)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        pnlMainCard.add(subPnlView, "card4");

        panel1.add(pnlMainCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 500, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashbordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashbordActionPerformed
        subPnlDashbord.setVisible(true);
        subPnlAdding.setVisible(false);
        subPnlView.setVisible(false);
    }//GEN-LAST:event_btnDashbordActionPerformed

    private void btnAddMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMemberActionPerformed
        subPnlDashbord.setVisible(false);
        subPnlAdding.setVisible(true);
        subPnlView.setVisible(false);
    }//GEN-LAST:event_btnAddMemberActionPerformed

    private void btnViewMemberDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMemberDetailsActionPerformed
        subPnlDashbord.setVisible(false);
        subPnlAdding.setVisible(false);
        subPnlView.setVisible(true);
    }//GEN-LAST:event_btnViewMemberDetailsActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearData();
    }//GEN-LAST:event_btnClearActionPerformed

    private void clearData(){
        txtId.setText("");
        txtName.setText("");
        txtContact.setText("");
        txtUserName.setText("");
        txtExpireDate.setText("");
        txtCardNumber.setText("");
        txtPassword1.setText("");
        txtExpireDate.setText("");
    }
    
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        try{
            
            Member member1=new Member(Integer.parseInt(txtId.getText()),txtName.getText(),txtContact.getText(),txtUserName.getText(),txtPassword1.getText(),new MemberShipCard(Integer.parseInt(txtCardNumber.getText()),txtExpireDate.getText()));
            ac.add(member1);
            
        }catch(NumberFormatException e){
            System.out.println(e);
        }
        
        clearData();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnViewMemberDataArrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMemberDataArrActionPerformed
        ac.viewMemberDetails();
    }//GEN-LAST:event_btnViewMemberDataArrActionPerformed

    private void btnSaveDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDBActionPerformed
        ac.InsertListDataToDatabase();
    }//GEN-LAST:event_btnSaveDBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMember;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDashbord;
    private javax.swing.JButton btnSaveDB;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnViewMemberDataArr;
    private javax.swing.JButton btnViewMemberDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel pnlLeftSide;
    private java.awt.Panel pnlMainCard;
    private java.awt.Panel subPnlAdding;
    private java.awt.Panel subPnlDashbord;
    private java.awt.Panel subPnlView;
    private javax.swing.JTextField txtCardNumber;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtExpireDate;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
